import 'dotenv/config';
import type { Page } from 'playwright';

// Inlined helper functions (avoid ESM resolution issues when used outside Playwright runtime)
function materialize(template: string, vars: Record<string, string>): string {
  return template.replace(/\{(\w+)\}/g, (_, k) => (k in vars ? vars[k] : `{${k}}`));
}

function materializeAll(list: ReadonlyArray<string>, vars: Record<string, string>): string[] {
  return list.map(t => materialize(t, vars));
}

export const CFG = {
  contactName: process.env.CONTACT_NAME || 'Twilio',
  headless: (process.env.HEADLESS || 'false').toLowerCase() === 'true',
  sessionDir: (process.env.SESSION_DIR || '~/.wapp-autoloop-session').replace('~', process.env.USERPROFILE || process.env.HOME || ''),
  cmds: {
    assignPriceProduct: process.env.CMD_ASSIGN_PRICE_PRODUCT || 'AssignPriceProduct',
    createChemicalProduct: process.env.CMD_CREATE_CHEMICAL_PRODUCT || 'CreateChemicalProduct',
    createCrop: process.env.CMD_CREATE_CROP || 'CreateCrop',
    createFertilizer: process.env.CMD_CREATE_FERTILIZER || 'CreateFertilizer',
    createPlannedCampaign: process.env.CMD_CREATE_PLANNED_CAMPAIGN || 'CreatePlannedCampaign',
    getChemicalProducts: process.env.CMD_GET_CHEMICAL_PRODUCTS || 'GetChemicalProducts',
    getCropDistribution: process.env.CMD_GET_CROP_DISTRIBUTION || 'GetCropDistribution',
    getCrops: process.env.CMD_GET_CROPS || 'GetCrops',
    getLastWork: process.env.CMD_GET_LAST_WORK || 'GetLastWork',
    getMinPrice: process.env.CMD_GET_MIN_PRICE || 'GetMinPrice',
    getPendingWorks: process.env.CMD_GET_PENDING_WORKS || 'GetPendingWorks',
    checkUnplannedFields: process.env.CMD_CHECK_UNPLANNED_FIELDS || 'CheckUnplannedFields',
    createPlannedWork: process.env.CMD_CREATE_PLANNED_WORK || 'CreatePlannedWork',
    filterFertilizers: process.env.CMD_FILTER_FERTILIZERS || 'FilterFertilizers',
    getActiveMatterChemicalProducts: process.env.CMD_GET_ACTIVE_MATTER_CHEMICAL_PRODUCTS || 'GetActiveMatterChemicalProducts',
    getChemicalProductsByClient: process.env.CMD_GET_CHEMICAL_PRODUCTS_BY_CLIENT || 'GetChemicalProductsByClient',
    getFertilizers: process.env.CMD_GET_FERTILIZERS || 'GetFertilizers',
    getLastPrice: process.env.CMD_GET_LAST_PRICE || 'GetLastPrice',
    getManufacturerProducts: process.env.CMD_GET_MANUFACTURER_PRODUCTS || 'GetManufacturerProducts',
    getPlannedCampaignsHistory: process.env.CMD_GET_PLANNED_CAMPAIGNS_HISTORY || 'GetPlannedCampaignsHistory',
    getPriceVariation: process.env.CMD_GET_PRICE_VARIATION || 'GetPriceVariation',
    getSeedsNeeded: process.env.CMD_GET_SEEDS_NEEDED || 'GetSeedsNeeded',
    goodbye: process.env.CMD_GOODBYE || 'Goodbye',
    greet: process.env.CMD_GREET || 'Greet',
    reportFinishedWork: process.env.CMD_REPORT_FINISHED_WORK || 'ReportFinishedWork',
    requestOtp: process.env.CMD_REQUEST_OTP || 'RequestOtp',
    searchProducts: process.env.CMD_SEARCH_PRODUCTS || 'SearchProducts',
    searchProductsCrops: process.env.CMD_SEARCH_PRODUCTS_CROPS || 'SearchProductsCrops',
    searchProductsFertilizers: process.env.CMD_SEARCH_PRODUCTS_FERTILIZERS || 'SearchProductsFertilizers'
  }
} as const;

export const VARS: Record<string, string> = {
  active_matter_name: process.env.VAR_ACTIVE_MATTER_NAME || 'diflufenican',
  amount_harvested: process.env.VAR_AMOUNT_HARVESTED || '8500',
  applied_dose: process.env.VAR_APPLIED_DOSE || '180',
  brand: process.env.VAR_BRAND || 'Bayer',
  chemical_product_name: process.env.VAR_CHEMICAL_PRODUCT_NAME || 'Roundup',
  client: process.env.VAR_CLIENT || 'AgroMartín SL',
  client_name: process.env.VAR_CLIENT_NAME || 'Automatización Clnt',
  composition: process.env.VAR_COMPOSITION || 'consumo humano',
  crop_name: process.env.VAR_CROP_NAME || 'maíz',
  depth: process.env.VAR_DEPTH || '25',
  destination: process.env.VAR_DESTINATION || 'consumo',
  farm_name: process.env.VAR_FARM_NAME || 'prueba',
  fertilizer_name: process.env.VAR_FERTILIZER_NAME || 'Nitrofoska',
  field_name: process.env.VAR_FIELD_NAME || 'campo',
  form_type: process.env.VAR_FORM_TYPE || 'líquido',
  fuel_used: process.env.VAR_FUEL_USED || '45.5',
  general_dose: process.env.VAR_GENERAL_DOSE || '300',
  manufacturer_name: process.env.VAR_MANUFACTURER_NAME || 'Mosaic Company',
  mode_of_action: process.env.VAR_MODE_OF_ACTION || 'sistémico',
  nitrogen_level: process.env.VAR_NITROGEN_LEVEL || '20',
  nombre_usuario_cliente: process.env.VAR_NOMBRE_USUARIO_CLIENTE || 'Automatización Clnt',
  price: process.env.VAR_PRICE || '340',
  product_name: process.env.VAR_PRODUCT_NAME || 'Trigo Filón',
  search_query: process.env.VAR_SEARCH_QUERY || 'Girasol',
  target_pest: process.env.VAR_TARGET_PEST || 'mildiu',
  type_fertilizer: process.env.VAR_TYPE_FERTILIZER || 'granulado',
  type_work: process.env.VAR_TYPE_WORK || 'SIEMBRA',
  variety_name: process.env.VAR_VARIETY_NAME || 'amarillo costeño',
  work_id: process.env.VAR_WORK_ID || '64f1b2c3d4e5f6a7b8c9d0e0',
  worked_hours: process.env.VAR_WORKED_HOURS || '6.5',
  price_date: 'hoy',

};

export const DEFAULT_VARS: Readonly<Record<string, string>> = { ...VARS };

export const setVar = (name: string, value: string) => {
  if (!name || !/^\w+$/.test(name)) throw new Error(`Nombre de variable inválido: "${name}"`);
  VARS[name] = String(value);
};

export const withVars = (vars: Record<string, string>) => {
  for (const [k, v] of Object.entries(vars)) setVar(k, String(v));
};

export function resetVarsToDefaults() {
  for (const [k, v] of Object.entries(DEFAULT_VARS)) {
    setVar(k, v);
  }
}

export const INTENTS_TEMPLATES = {
  assignPriceProduct: [
    'Hola Luca, asigna un precio de {price}€/tonelada al {product_name} {price_date}',
    'Hola Luca, asigna un precio de {price}€/tonelada al {product_name} {price_date}',
    'Hola Luca, acabo de recibir una factura a {price}€/tonelada el {product_name} a fecha {price_date}',
    'Establece {price} €/tn para el {product_name} {price_date}',
    'Establece {price} €/tn para el {product_name} {price_date}',
    'Hola Luca, el {product_name} queda a {price} euros por tonelada desde el {price_date}',
    'Sube el precio del {product_name} a {price} €/tn {price_date}',
    'Asigna para la {product_name} un precio de {price} euros/tn con fecha de {price_date}',
    'Coloca {price} €/tonelada al {product_name} a partir del {price_date}',
    'Luca, el precio del {product_name} será de {price} €/tn desde {price_date}',
    'Para el {product_name}, pon {price} euros por tonelada {price_date}',
    'Ponme {price} euros/tn a la {product_name} de este año {price_date}',
    'Quiero que el precio de la {product_name} sea de {price} €/tn a fecha {price_date}',
    'El {product_name} sube a {price} €/tonelada desde el {price_date}',
    'Fija para la {product_name} un precio de {price} €/tn {price_date}',
    'Quiero {price} euros por tonelada para la {product_name} del {price_date}',
    'Pon el {product_name} a {price} €/tn desde {price_date}',
    'Luca, actualiza el precio de la {product_name} a {price} euros/tn, fecha {price_date}',
    'Para la {product_name}, establece {price} €/tonelada desde el {price_date}',
    'Sube la {product_name} a {price} €/tn {price_date}',
    '{product_name} a {price} €/tonelada desde el {price_date}',
    'Quiero asignar para el {product_name} un precio de {price} euros/tn {price_date}',
    'Pon el {product_name} a {price} €/tn, fecha {price_date}',
    'Fija {price_date} {price} euros por tonelada para la {product_name}'
  ],
  createChemicalProduct: [
    'quiero registrar un producto químico',
    'registrar producto químico',
    'crear producto químico',
    'quiero añadir un nuevo producto químico',
    'agrega un producto químico',
    'necesito crear un producto químico',
    'crear un nuevo producto químico',
    'voy a crear un producto químico',
    'quiero crear un producto químico desde cero',
    'me gustaría registrar un nuevo producto químico',
    'quiero dar de alta un producto químico',
    'agrega un nuevo producto químico',
    'vamos a crear un producto químico',
    'registrar un nuevo producto químico',
    'me gustaría añadir otro producto químico',
    'podemos crear un producto químico?',
    'deseo crear un producto químico',
    'genera un producto químico',
    'alta de un producto químico',
    'crea un producto químico nuevo',
    'crea un nuevo producto químico',
    'registra un producto químico',
    'dame de alta un producto químico',
    'quiero cargar un nuevo producto químico',
    'agregar producto químico',
    'necesito dar de alta un producto químico',
    'quiero introducir un nuevo producto químico',
    'vamos a registrar un producto químico',
    'registrar un producto químico nuevo',
    'crea producto químico',
    'quiero crear un nuevo producto químico en el sistema',
    'me gustaría crear un producto químico nuevo',
    'Añade el fitosanitario {chemical_product_name}',
    'Quiero registrar el pesticida {chemical_product_name} contra {target_pest}',
    'Mete el herbicida {chemical_product_name} de tipo {mode_of_action}',
    'Apunta el plaguicida {chemical_product_name} para {target_pest} de la marca {brand}',
    'Apunta el plaguicida {chemical_product_name} para {target_pest} de la marca {brand}',
    'Crea un insecticida llamado {chemical_product_name} que sea {mode_of_action}',
    'Dar de alta el fungicida {chemical_product_name} para {target_pest} en {brand}',
    'Registra un producto de control de plagas, {chemical_product_name}, {mode_of_action}',
    'Añade el herbicida {chemical_product_name} contra {target_pest}',
    'Meter insecticida {chemical_product_name} de {brand} que sea {mode_of_action}',
    'Apunta el plaguicida {chemical_product_name} para {target_pest}',
    'Crear el fitosanitario {chemical_product_name} {mode_of_action} para {target_pest}',
    'Dar de alta un fungicida {chemical_product_name} de {brand}',
    'Registra herbicida {chemical_product_name} de {brand} para {target_pest}',
    'Quiero añadir insecticida {chemical_product_name} para {target_pest} {mode_of_action}',
    'Apuntar plaguicida {chemical_product_name} {mode_of_action} en cuenta de {client}',
    'Mete fungicida {chemical_product_name} para {target_pest} de {brand}',
    'Crear pesticida {chemical_product_name} para {target_pest} en {client}',
    'Añadir producto de control de plagas {chemical_product_name} para {target_pest}',
    'Apuntar herbicida {chemical_product_name} {mode_of_action}',
    'Mete insecticida {chemical_product_name} de {brand} contra {target_pest}',
    'Registrar el plaguicida {chemical_product_name} {mode_of_action}',
    'Dar de alta el fitosanitario {chemical_product_name} de {brand}',
    'Añade pesticida {chemical_product_name} {mode_of_action} para {target_pest}',
    'Apuntar herbicida {chemical_product_name} para {target_pest} de {brand}',
    'Mete fungicida {chemical_product_name} {mode_of_action}',
    'Perdona, cambio la marca del insecticida {chemical_product_name} a {brand}',
    'Me refería a que el fungicida es {mode_of_action}, no preventivo',
    'Corrijo, el plaguicida {chemical_product_name} es para {target_pest}',
    'El producto de control de plagas {chemical_product_name} es {mode_of_action} de {brand}',
    'Quiero registrar pesticida {chemical_product_name} para {target_pest} de {brand}',
    'Registra el herbicida {chemical_product_name} de {brand} por {price} euros',
    'Añade el plaguicida {chemical_product_name} contra {target_pest} {mode_of_action} a {price}€',
    'Para {client} mete el fungicida {chemical_product_name} {mode_of_action} de {brand}',
    'Dar de alta insecticida {chemical_product_name} para {target_pest} en {client} por {price} euros',
    'Crear fitosanitario {chemical_product_name} {mode_of_action} contra {target_pest} de {brand} a {price}',
    'Registra pesticida {chemical_product_name} de {brand} para {target_pest} en {client}',
    'Apunta producto químico {chemical_product_name} {mode_of_action} por {price}',
    'Añade insecticida {chemical_product_name} para {target_pest} de {brand} en {client}',
    'Necesito registrar herbicida {chemical_product_name} {mode_of_action} contra {target_pest} por {price} euros',
    'Para el cliente {client}, crea el fungicida {chemical_product_name} de {brand} a {price}',
    'Dar de alta plaguicida {chemical_product_name} para {target_pest} de {brand} con precio {price}',
    'Registrar fitosanitario {chemical_product_name} en {client} {mode_of_action} por {price} euros',
    'Crear para el fabricante {brand}, el producto químico {chemical_product_name}, con el precio de {price} para el cliente {client}',
    'Para el fabricante {brand}, crear el producto químico {chemical_product_name}, con el precio de {price} para el cliente {client}',
    'Luca crea para el fabricante {brand}, el producto quimico {chemical_product_name}, con el precio de {price} para el cliente {client}',
    'Necesito agregar para el fabricante {brand}, el producto químico {chemical_product_name}, con el precio de {price} para el cliente {client}',
    'Crear para el fabricante {brand}, el producto químico {chemical_product_name}, con el precio de {price} para el cliente {client}',
    'Crea el producto químico {chemical_product_name}, para el fabricante {brand}, con el precio de {price} para el cliente {client}',
    'Oye luca crea el producto quimico {chemical_product_name}, para el fabricante {brand}, con el precio de {price} para el cliente {client}',
    'Agrega el producto químico {chemical_product_name}, para el fabricante {brand}, con el precio de {price} para el cliente {client}',
    'Quiero agregar para el fabricante {brand}, el producto quimico {chemical_product_name}, con el precio de {price} para el cliente {client}',
    'Por favor registra el producto químico {chemical_product_name}, para el fabricante {brand}, con el precio de {price} para el cliente {client}',
    'Necesito guardar el producto químico {chemical_product_name}, para el fabricante {brand}, con el precio de {price} para el cliente {client}',
    'Luca aguardar para el fabricante {brand}, el producto químico {chemical_product_name}, con el precio de {price} para el cliente {client}',
    'Luca necesito agregar para el fabricante {brand}, el producto químico {chemical_product_name}, con el precio de {price} para el cliente {client}',
    'Asocia para el fabricante {brand}, el producto químico {chemical_product_name}, con el precio de {price} para el cliente {client}',
    'Facilita el producto químico {chemical_product_name}, para el fabricante {brand}, con el precio de {price} para el cliente {client}',
    'Oye luca necesito crear el producto químico {chemical_product_name}, para el fabricante {brand}, con el precio de {price} para el cliente {client}',
    'Crear para el fabricante {brand}, el producto quimico {chemical_product_name}, con el precio de {price}',
    'Crea para el fabricante {brand}, el producto quimico {chemical_product_name}, con precio de {price} para {client}',
    'Crea para el fabricante {brand}, el producto químico {chemical_product_name}, con el precio de {price} para {client}',
    'Para el fabricante {brand}, crea el producto quimico {chemical_product_name} a {price} para {client}',
    'Para {client}, crear producto químico {chemical_product_name} del fabricante {brand} con precio {price}',
    'Crear producto quimico {chemical_product_name} con precio {price} para {client} del fabricante {brand}',
    'Crear para el fabricante {brand}, el producto químico {chemical_product_name}, con precio de {price} para {client}'
  ],
  createCrop: [
    'quiero registrar un cultivo',
    'registrar cultivo',
    'crear cultivo',
    'quiero añadir un nuevo cultivo',
    'agrega un cultivo',
    'necesito crear un cultivo',
    'crear un nuevo cultivo',
    'voy a crear un cultivo',
    'quiero crear un cultivo desde cero',
    'me gustaría registrar un nuevo cultivo',
    'quiero dar de alta un cultivo',
    'agrega un nuevo cultivo',
    'vamos a crear un cultivo',
    'registrar un nuevo cultivo',
    'me gustaría añadir otro cultivo',
    'podemos crear un cultivo?',
    'deseo crear un cultivo',
    'generar un cultivo',
    'alta de un cultivo',
    'crea un cultivo nuevo',
    'crea un nuevo cultivo',
    'registra un cultivo',
    'dame de alta un cultivo',
    'quiero cargar un nuevo cultivo',
    'agregar cultivo',
    'necesito dar de alta un cultivo',
    'quiero introducir un nuevo cultivo',
    'vamos a registrar un cultivo',
    'registrar un cultivo nuevo',
    'crea cultivo',
    'quiero crear un nuevo cultivo en el sistema',
    'me gustaría crear un cultivo nuevo',
    'Luca, registra cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand} y cliente {client}.',
    'Guardar cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand}.',
    'Luca, registra cultivo {crop_name}, destino {destination}, marca {brand}.',
    'Luca, agrega cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand} para cliente {client}.',
    'Hola LUCA, registrar cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand} para el cliente {client}',
    'Guardar cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand} para el cliente {client}',
    'Guardar cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand}, para el cliente {client}',
    'Guardar cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand} con el cliente {client}',
    'Necesito guardar cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand} y el cliente {client}',
    'Luca, agrega cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand} cliente {client}',
    'Luca, agrega cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand} con cliente {client}',
    'Hola LUCA, registrar cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand} para el cliente {client}',
    'Guardar cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand} para el cliente {client}',
    'Guardar cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand}, para el cliente {client}',
    'Guardar cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand} con el cliente {client}',
    'Necesito guardar cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand} y el cliente {client}',
    'Luca, agrega cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand} cliente {client}',
    'Luca, agrega cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand} con cliente {client}',
    'Hola luca, queiro crear el cultivo {crop_name} con variedad {variety_name} con destino {destination} y marca {brand} con el cliente {client}',
    'luca, me puedes registrar el cultivo {crop_name} con variedad {variety_name} con destino {destination} y marca {brand} con el cliente {client}',
    'luca, quiero regiatrar el cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand} con cliente {client}',
    'hola luca, agregame el cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand} con cliente {client}',
    'Luca registrar cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand} con cliente {client}',
    'Guardar cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand} cliente {client}',
    'Hola luca, mete cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand} para cliente {client}',
    'Luca, agregá cultivo {crop_name} con variedad {variety_name}, destino {destination}, marca {brand}, cliente {client}',
    'Luca quiero guardar cultivo {crop_name} variedad {variety_name} destino {destination} marca {brand} con cliente {client}',
    'Agregame cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand}, cliente {client}',
    'Necesito registrar cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand} con cliente {client}',
    'Luca, mete cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand} cliente {client}',
    'Guardar cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand} para el cliente {client}',
    'Hola Luca, quiero registrar cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand} cliente {client}',
    'Luca, apúntame cultivo {crop_name} variedad {variety_name} destino {destination} marca {brand} con cliente {client}',
    'Guardar cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand}, cliente {client}',
    'Luca registra cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand}, cliente {client}',
    'Necesito crear cultivo {crop_name} con variedad {variety_name}, destino {destination}, marca {brand} con cliente {client}',
    'Hola luca, guarda cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand} con cliente {client}',
    'Luca, quiero meter cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand} con cliente {client}',
    'Apunta cultivo {crop_name} con variedad {variety_name}, destino {destination}, marca {brand} cliente {client}',
    'Guardar cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand}, cliente {client}',
    'Luca agrega cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand} para cliente {client}',
    'Hola luca, necesito registrar cultivo {crop_name}, variedad {variety_name}, destino {destination}, marca {brand} con cliente {client}',
  
  
  ],
  createFertilizer: [
    'quiero registrar un fertilizante',
    'registrar fertilizante',
    'crear fertilizante',
    'quiero añadir un nuevo fertilizante',
    'agrega un fertilizante',
    'necesito crear un fertilizante',
    'crear un nuevo fertilizante',
    'voy a crear un fertilizante',
    'quiero crear un fertilizante desde cero',
    'me gustaría registrar un nuevo fertilizante',
    'quiero dar de alta un fertilizante',
    'agrega un nuevo fertilizante',
    'vamos a crear un fertilizante',
    'registrar un nuevo fertilizante',
    'me gustaría añadir otro fertilizante',
    'podemos crear un fertilizante?',
    'deseo crear un fertilizante',
    'generar un fertilizante',
    'alta de un fertilizante',
    'crea un fertilizante nuevo',
    'crea un nuevo fertilizante',
    'registra un fertilizante',
    'dame de alta un fertilizante',
    'quiero cargar un nuevo fertilizante',
    'agregar fertilizante',
    'necesito dar de alta un fertilizante',
    'quiero introducir un nuevo fertilizante',
    'vamos a registrar un fertilizante',
    'registrar un fertilizante nuevo',
    'crea fertilizante',
    'quiero crear un nuevo fertilizante en el sistema',
    'me gustaría crear un fertilizante nuevo',
    'Quiero registrar el {fertilizer_name} como fertilizante {type_fertilizer}, del fabricante {brand}',
    'Quiero registrar el fertilizante {fertilizer_name} de tipo {type_fertilizer} de la marca {brand}',
    'Quiero registrar el fertilizante {fertilizer_name} como {type_fertilizer} de la marca {brand}',
    'Apúntame un abono {fertilizer_name} para {composition}',
    'Añade el fertilizante {fertilizer_name} de {brand}',
    'Necesito dar de alta un abono {type_fertilizer} con {composition}',
    'Registra un nutriente {fertilizer_name} para {composition}',
    'Crea el fertilizante {fertilizer_name} marca {brand}',
    'Me gustaría meter un abono {type_fertilizer} llamado {fertilizer_name}',
    'Anota un fertilizante {type_fertilizer} de {brand} con fórmula {composition}',
    'Para la finca, crea el abono {fertilizer_name} de tipo {type_fertilizer}',
    'Dar de alta un corrector {fertilizer_name} de {brand} con {composition}',
    'Añadir un fertilizante {type_fertilizer} {fertilizer_name} para {composition}',
    'Crea un abono {type_fertilizer} llamado {fertilizer_name} con fórmula {composition}',
    'Registra un nutriente {fertilizer_name} para {composition} marca {brand}',
    'Meter un fertilizante {type_fertilizer} {fertilizer_name}',
    'Dar de alta un abono {type_fertilizer} de {brand}',
    'Crear fertilizante {fertilizer_name} marca {brand}',
    'Apuntar un nutriente {fertilizer_name} para {composition}',
    'Añade fertilizante {fertilizer_name} para {composition}',
    'Registra un abono {fertilizer_name} de {brand} con fórmula {composition}',
    'Crea fertilizante {fertilizer_name} marca {brand}',
    'Perdona, la marca del abono es {brand}',
    'Me refería al tipo de fertilizante {type_fertilizer}',
    'Cambia la fórmula del nutriente a {composition}',
    'Para el cliente {client}, registra fertilizante {fertilizer_name}',
    'Cliente {client}, dar de alta abono {fertilizer_name} {type_fertilizer}',
    'Añadir para {client} el fertilizante {fertilizer_name} {type_fertilizer}',
    'Registrar para {client} un nutriente {fertilizer_name} para {composition}',
    'Crear abono {type_fertilizer} {fertilizer_name} para {composition}',
    'Apúntame un corrector {fertilizer_name} de {brand}',
    'Dar de alta un fertilizante {fertilizer_name} {type_fertilizer}'
  ],
  createPlannedCampaign: [
    'Hola Luca, pon en la parcela {field_name} el cultivo de {crop_name}',
    'pon {crop_name} en la parcela {field_name}',
    'planifica {crop_name} en {farm_name}',
    'pon {crop_name} variedad {variety_name} en la parcela {field_name}',
    'planifica {crop_name} variedad {variety_name} en la parcela {field_name}',
    'mete {crop_name} {variety_name} en {farm_name} y {farm_name}',
    'pon {variety_name} de {crop_name} en la parcela {field_name}',
    'quiero {crop_name} {variety_name} en la parcela {field_name}',
    'este año quiero {crop_name} {variety_name} en {farm_name}',
    'pon {crop_name} {variety_name} en la parcela {field_name} y {field_name}',
    'planifica {crop_name} {variety_name} en {farm_name}',
    'mete {crop_name} {variety_name} en {farm_name}',
    'planifica {crop_name} {variety_name} en {farm_name} y {farm_name}',
    'planifica {crop_name} en {farm_name}',
    'planifica {crop_name} {variety_name} en {farm_name} {field_name}',
    'para {client} planifica {crop_name} {variety_name} en {farm_name} {field_name}',
    'pon {crop_name} en {farm_name}',
    'quiero poner {crop_name}, {crop_name} y {crop_name}',
    'añade {crop_name} {variety_name} en {field_name}',
    'crear una campaña planificada',
    'quiero crear una campaña planificada',
    'añade una campaña planificada',
    'agregar una campaña planificada',
    'crear campaña planificada',
    'planificar una campaña'
  ],
  getChemicalProducts: [
    'Dame los productos químicos que tengo',
    '¿Cuáles son los químicos que manejo?',
    'Muéstrame la lista de productos químicos',
    'Químicos disponibles',
    '¿Cuál es mi inventario de químicos?',
    'Muéstrame qué plaguicidas tengo registrados ahora mismo',
    '¿Qué productos químicos tengo actualmente en la finca?',
    'Quiero consultar los pesticidas que tengo registrados',
    'Lista todos los agroquímicos que tengo ahora',
    '¿Me puedes mostrar los tratamientos fitosanitarios que tengo en uso?',
    'Dime qué insecticidas y fungicidas tengo registrados',
    '¿Qué productos para plagas tengo registrados en mis cultivos?',
    'Muestra los químicos agrícolas que tengo actualmente',
    'Quiero ver qué herbicidas y fungicidas tengo ahora mismo registrados',
    'Lista todos los tratamientos que tengo para protección vegetal',
    'Consulta rápida de los pesticidas que estoy usando',
    '¿Me podrías enseñar los agroquímicos que tengo en mis parcelas?',
    'Consulta qué productos fitosanitarios tengo activos ahora',
    'Lista todos los productos químicos que utilizo en mis cultivos',
    'Dime qué insecticidas tengo registrados en la finca ahora',
    '¿Qué fungicidas y herbicidas tengo registrados actualmente?',
    'Muéstrame los tratamientos agrícolas disponibles',
    'Quiero consultar los pesticidas registrados ahora mismo',
    '¿Qué agroquímicos tengo disponibles para aplicar en mis campos?',
    'Lista todos los productos para plagas que tengo en la finca ahora',
    'Muéstrame los productos químicos agrícolas que tengo en uso',
    'Enséñame el inventario de químicos agrícolas que poseo',
    '¿Podrías listar mis productos fitosanitarios?',
    'Necesito revisar los químicos que tengo disponibles hoy',
    'Quiero saber qué plaguicidas y fungicidas están activos en mis cultivos'
  ],
  getCropDistribution: [
    'Hola Luca, ¿qué distribución de cultivos tengo este año?',
    'Luca, muéstrame los cultivos de este año',
    '¿Cómo están repartidos mis cultivos?',
    'Quiero ver qué cultivos tengo y en qué campos',
    '¿Qué superficie tengo sembrada y con qué?',
    '¿Cuánto espacio tengo cultivado este año?'
  ],
  getCrops: [
    'dame la lista de cultivos',
    'dame los cultivos de {client_name}',
    'dame los cultivos de {client_name}',
    'dame la lista de cultivos de {client_name}',
    'quiero ver los cultivos',
    'muéstrame los cultivos disponibles',
    'ver los cultivos del cliente {client_name}',
    'para el cliente {client_name}, cuáles son sus cultivos',
    'necesito los cultivos del cliente {client_name}',
    'ver cultivos de {client_name}',
    'Muéstrame qué cultivos tengo ahora mismo en la finca.',
    '¿Qué plantaciones tengo registradas?',
    'Listar todos los cultivos que tengo actualmente.',
    'Quiero consultar las plantas que tengo en mis parcelas.',
    '¿Puedes mostrarme las cosechas que tengo disponibles?',
    'Dime qué cultivos están registrados en mi cuenta.',
    'Lista las siembras que tengo activas.',
    'Ver las especies vegetales que tengo en mis campos.',
    '¿Qué vegetales tengo plantados actualmente?',
    'Consultar las plantaciones que maneja {client_name}.',
    'Mostrarme qué cultivos tiene registrados {client_name}.',
    '¿Qué especies agrícolas tiene registradas {client_name}?',
    'Quisiera ver las cosechas que tiene ahora {client_name}.',
    'Dime qué plantas tiene disponibles {client_name}.',
    'Listar las siembras registradas para {client_name}.',
    '¿Puedes mostrarme los cultivos que maneja {client_name}?',
    'Consulta rápida de vegetales que tiene {client_name}.',
    'Mostrar qué plantaciones tiene actualmente {client_name}.',
    'Listar todas las especies vegetales de {client_name}.',
    'Dime las cosechas que tiene {client_name}.',
    '¿Qué cultivos tiene ahora mismo {client_name}?',
    'Kiero consultar las plantas que tiene registradas {client_name}.',
    'Mostrar las siembras activas para {client_name}.',
    'Listar vegetales disponibles en la finca de {client_name}.',
    '¿Qué especies agrícolas tiene registradas {client_name}?',
    'Quiero ver qué plantaciones tiene actualmente {client_name}.',
    'Muéstrame los cultivos que maneja {client_name}.',
    'Consultar plantas registradas por {client_name}.',
    'Dime qué cosechas tiene ahora {client_name}.',
    'Ver las especies vegetales registradas para {client_name}.',
    'Listame los cultivos de {client_name}.',
    'Muéstrame las plantaciones de {client_name}.',
    'Dame un informe de los cultivos de {client_name}.',
    '¿Qué tiene sembrado {client_name}?',
    'Consulta los cultivos registrados por {client_name}.',
    'Ver cultivos actuales de {client_name}.',
    '¿Puedes mostrarme las siembras de {client_name}?',
    'Quiero conocer los cultivos de {client_name}.',
    'Lista las cosechas de {client_name}.',
    '¿Qué plantaciones tiene {client_name}?',
    'Necesito ver los cultivos de {client_name}.',
    'Consulta rápida de las siembras de {client_name}.',
    'Dame la información de cultivos de {client_name}.',
    'Mostrar plantaciones registradas para {client_name}.',
    '¿Cuáles son los cultivos activos de {client_name}?',
    'Ver especies cultivadas por {client_name}.',
    'Lista de plantas registradas de {client_name}.',
    'Cultivos actuales de {client_name}.',
    '¿Me puedes decir qué tiene sembrado {client_name}?',
    'Quiero ver las plantaciones de {client_name}.',
    'Mostrar cultivos asociados a {client_name}.',
    '¿Qué está cultivando {client_name}?',
    'Dame la lista de siembras de {client_name}.',
    'Necesito saber qué cultiva {client_name}.',
    '¿Qué plantaciones tiene registradas {client_name}?',
    'Ver los cultivos de {client_name}.',
    'Información sobre las siembras de {client_name}.',
    'Lista los cultivos que maneja {client_name}.',
    '¿Cuáles son las plantaciones de {client_name}?',
    'Muéstrame qué está cultivando {client_name}.',
    'dame los cultivos de {client_name}',
    'dame los cultivos de {client_name}',
    'dame los cultivos de {client_name}',
    'dame los cultivos de {client_name}',
    'dame los cultivos de {client_name}',
    'dame los cultivos de {client_name}',
    'dame los cultivos de {client_name}',
    'dame los cultivos de {client_name}',
    'dame los cultivos de {client_name}',
    'dame los cultivos de {client_name}',
    'dame los cultivos de {client_name}',
    'dame los cultivos de {client_name}',
    'dame los cultivos de {client_name}',
    'dame los cultivos de {client_name}',
    'dame los cultivos de {client_name}'
  ],
  getLastWork: [
    'Muéstrame el último trabajo',
    'Quiero ver el último trabajo',
    '¿Cuál fue el último trabajo realizado?',
    'Último trabajo en {farm_name}',
    'Último trabajo del {field_name}',
    'Último trabajo en la granja {farm_name}',
    'Enséñame el último trabajo del campo {field_name}',
    'Último trabajo de {client_name}',
    'Último trabajo de {client_name} en {farm_name}',
    'Último trabajo en {farm_name} del {field_name}',
    'Quiero el último trabajo de {client_name} en {farm_name} del {field_name}',
    'Dame el último trabajo para el campo {field_name} de la explotación {farm_name}',
    '¿Qué se hizo por última vez en el campo {field_name} de {farm_name}?',
    'Último trabajo del cliente {client_name} en {farm_name} {field_name}',
    'Ver último trabajo del campo {field_name}',
    'Ver el último trabajo en la explotación {farm_name}',
    'Último trabajo para el cliente {client_name}',
    'Muestra el último trabajo en {farm_name} campo {field_name}',
    '¿Cuál es el último trabajo de {client_name} en {farm_name} {field_name}?',
    'Necesito el último trabajo realizado en {farm_name} del campo {field_name}',
    'Último trabajo realizado en {farm_name} {field_name}',
    '¿Tienes el último trabajo para {farm_name} {field_name}?',
    'Dame el último trabajo (me falta el campo)',
    'Quiero el último trabajo de esta finca {farm_name} (falta el campo)',
    'Último trabajo del cliente {client_name} (falta granja y campo)',
    'Último trabajo en la granja {farm_name} (falta campo)',
    'El último trabajo del campo {field_name} (falta granja)',
    'Último trabajo (falta todo)'
  ],
  getMinPrice: [
    'Hola Luca, cuál es el precio mínimo del {search_query}?',
    'Luca, dime el valor más bajo que ha tenido el {search_query}',
    '¿A cómo ha estado el {search_query} en su punto más bajo?',
    '¿Cuál fue el precio mínimo del {search_query}?',
    'Luca, cuánto ha sido lo más barato que me ha costado el {search_query}?',
    'cuál es el menor precio registrado del {search_query}?',
    'Hola Luca, cuál es el precio mínimo del {search_query} para {client_name}?',
    'Luca, dime el valor más bajo que ha tenido el {search_query} para {client_name}',
    '¿A cómo ha estado el {search_query} en su punto más bajo para {client_name}?',
    'Para {client_name}, ¿cuál fue el precio mínimo del {search_query}?',
    'Luca, para el cliente {client_name} cuánto ha sido lo más barato del {search_query}?',
    'precio mínimo del {search_query} de {client_name}',
    '{client_name} precio mínimo {search_query}',
    'necesito saber el precio mínimo del {search_query} para {client_name}',
    'quiero consultar el mínimo del {search_query} para {client_name}',
    '{client_name} ¿cuál es el precio más bajo del {search_query}?',
    'Hola Luca, cuál es el precio mínimo del {search_query} para el cliente {client_name}?',
    '¿Podrías indicarme cuál ha sido el precio más económico de la {search_query}?',
    'Necesito información sobre el mínimo histórico del {search_query}',
    'En qué momento la {search_query} alcanzó su precio más bajo',
    'Consulta de precio mínimo para {search_query}',
    '¿Sabes cuál es el precio más económico al que se ha vendido el {search_query}?',
    'Para {client_name}, ¿cuál es el valor mínimo registrado del {search_query}?',
    'Dime el mejor precio que puedes ofrecerle a {client_name} para {search_query}',
    'Mínimo histórico de {search_query} para la cuenta de {client_name}',
    'El cliente {client_name} quiere saber el precio más bajo del {search_query}',
    '{client_name} solicita información sobre el mínimo del {search_query}',
    '¿A cuánto ha llegado a bajar el {search_query} para {client_name}?',
    'Luca, ¿cuál es el menor precio que ha tenido la {search_query} en nuestra base de datos?',
    '¿Me puedes decir a qué precio mínimo ha estado el {search_query} para {client_name}?',
    'Búscame el mínimo histórico del {search_query} para el cliente {client_name}',
    '{client_name} necesita saber cuándo estuvo más barato el {search_query}',
    'Hola Luca, cuál es el precio mínimo del {search_query} para {client_name}?'
  ],
  getPendingWorks: [
    'Hola Luca, ¿qué trabajos tengo para hacer hoy?',
    '¿Qué trabajos tengo hoy?',
    '¿Qué tareas hay hoy en los campos?',
    '¿Qué fertilizaciones hay programadas para hoy?',
    'Luca, dime los trabajos pendientes',
    '¿Qué trabajos están por hacer?',
    '¿Qué tareas hay programadas en mis campos?',
    '¿Cuántos trabajos hay pendientes?',
    'Hola Luca, ¿qué trabajos tiene el cliente {client_name} para hoy?',
    'Hola Luca, ¿qué trabajos tiene el cliente {client_name} del tipo {type_work}?',
    '¿Qué trabajos tengo del tipo {type_work}?',
    'Luca, muéstrame las tareas pendientes de {client_name}.',
    '¿Hay trabajos de {type_work} para el cliente {client_name}?',
    'Necesito saber los trabajos que faltan para {client_name}.',
    '¿Qué tareas quedan pendientes para {type_work} hoy?',
    '¿Cuáles son los trabajos de {client_name} del tipo {type_work}?',
    'Luca, ¿puedes decirme si hay algo pendiente con {client_name}?',
    '¿Qué trabajos hay sin terminar?',
    '¿Qué labores están agendadas para hoy?',
    '¿Hay alguna tarea pendiente de {type_work}?',
    'Quiero ver las tareas del cliente {client_name}.',
    '¿Qué trabajos están agendados con {client_name}?',
    'Luca, necesito la lista de tareas pendientes de {type_work}.',
    'Dime qué actividades tengo hoy con {client_name}.',
    '¿Qué trabajos de {type_work} tengo para hoy?',
    '¿Hay trabajos pendientes para {client_name}?',
    'Consulta las tareas programadas para {client_name}.',
    '¿Qué trabajos quedan por hacer del tipo {type_work}?',
    'Luca, muéstrame las tareas pendientes de {type_work}.',
    'Quiero ver los trabajos programados de {client_name}.',
    '¿Qué actividades tengo con {client_name} hoy?',
    '¿Hay trabajos de {type_work} para hoy?',
    '¿Qué trabajos tiene {client_name} para el día?',
    'Luca, dime qué labores hay pendientes con {type_work}.',
    '¿Cuáles son las tareas que faltan por realizar?',
    'Hola Luca, tengo algún trabajo planificado?'
  ],
  checkUnplannedFields: [
    'Hola Luca, ¿me queda algún campo sin planificar?',
    'Luca, ¿tengo campos sin asignar cultivo?',
    '¿Hay algún campo que no tenga campaña este año?',
    'Dime si tengo algún campo que no esté planificado',
    'Luca, quiero saber si todos mis campos están cubiertos',
    '¿Todos los campos tienen cultivos asignados?',
    'Hola Luca, tengo todos los cultivos planificados?',
    '¿Me queda algún campo para asignar cultivo?',
    '¿Tengo campos pendientes sin planificar?'
  ],
  createPlannedWork: [
    'crear un trabajo planificado',
    'planificar un trabajo',
    'quiero crear un trabajo en una campaña'
  ],
  filterFertilizers: [
    'qué fertilizantes con {nitrogen_level}% de nitrógeno tengo',
    'muéstrame los fertilizantes líquidos',
    'quiero ver abonos inorgánicos',
    'qué fertilizantes con más de {nitrogen_level}% de nitrógeno tengo disponibles',
    'dime los fertilizantes que tienen nitrógeno {nitrogen_level}',
    'fertilizantes con nitrógeno del {nitrogen_level}%',
    'dime qué fertilizantes tienen forma {form_type}',
    'qué fertilizantes con tipo {type_fertilizer} tengo creados',
    'Hola Luca, que fertilizantes con {nitrogen_level}% de nitrógeno tengo creados?',
    'Hola Luca, muéstrame los fertilizantes con forma {form_type} que tengo.',
    'Hola Luca, quiero ver los fertilizantes con tipo {type_fertilizer} que tengo.',
    'Hola Luca, qué fertilizantes con {nitrogen_level}% de nitrógeno tengo disponibles?',
    'Hola Luca, dime los fertilizantes que tienen nitrógeno {nitrogen_level}.',
    'Hola Luca, fertilizantes con nitrógeno del {nitrogen_level}%.',
    'fertilizantes con {nitrogen_level}% de nitrógeno',
    'fertilizantes con nitrógeno al {nitrogen_level} por ciento',
    'fertilizantes con porcentaje de nitrógeno igual a {nitrogen_level}',
    'fertilizantes con nitrógeno del {nitrogen_level}%',
    'fertilizantes que contienen {nitrogen_level} porciento de nitrógeno',
    'fertilizantes con concentración de nitrógeno {nitrogen_level}',
    'fertilizantes donde el nitrógeno sea {nitrogen_level}%',
    'qué fertilizantes tengo con exactamente {nitrogen_level} por ciento de nitrógeno',
    'muéstrame los fertilizantes con nitrógeno igual a {nitrogen_level}%',
    'abonos con nitrógeno del {nitrogen_level}%',
    'qué abonos tienen {nitrogen_level}% de nitrógeno',
    'Luca, muéstrame los fertilizantes que contienen {nitrogen_level}% de nitrógeno',
    'Hola Luca, necesito ver fertilizantes con {nitrogen_level} porciento de nitrógeno',
    'Luca, qué abonos tienen exactamente {nitrogen_level}% de nitrógeno',
    'Luca, enséñame los fertilizantes con concentración de nitrógeno del {nitrogen_level}%',
    'Luca, quiero ver los fertilizantes donde el nitrógeno sea {nitrogen_level}%',
    'Luca, fertilizantes con nitrógeno al {nitrogen_level}%',
    'Luca, qué fertilizantes tengo registrados con {nitrogen_level}% de nitrógeno',
    'Dime Luca, qué abonos con nitrógeno del {nitrogen_level}% tengo disponibles',
    'Luca, fertilizantes con nitrógeno igual a {nitrogen_level}',
    'Luca, lista los fertilizantes que contengan {nitrogen_level} porciento de nitrógeno',
    'Hola Luca, ¿qué fertilizantes usan nitrógeno del {nitrogen_level}%?',
    'Luca, quiero consultar los fertilizantes que tienen {nitrogen_level}% de nitrógeno',
    'Luca, filtra los abonos con nivel de nitrógeno de {nitrogen_level}%',
    'Luca, muéstrame solo los fertilizantes que tienen {nitrogen_level}% de nitrógeno',
    'Luca, qué fertilizantes tengo creados con una concentración de {nitrogen_level}% en nitrógeno',
    'Luca, lista de abonos que tengan nitrógeno del {nitrogen_level} por ciento, por favor',
    'Luca, dame los fertilizantes con nitrógeno {nitrogen_level}'
  ],
  getActiveMatterChemicalProducts: [
    'Hola Luca, que productos tienen {active_matter_name}?',
    'Hola luca, que productos tienen {active_matter_name}?',
    'Hola Luca, que producto tiene {active_matter_name}?',
    'Hola Luca, que producto tiene {active_matter_name}?',
    'Hola Luca, que producto tiene {active_matter_name}?Pyraclostrobin',
    'Luca, dime cuántos productos contienen {active_matter_name}',
    'Que herbicidas tienen {active_matter_name}?',
    'Hola Luca, listado de productos con {active_matter_name}',
    'Cuántos productos contienen {active_matter_name}?',
    'Luca, que fitosanitarios tienen {active_matter_name}?',
    'Hola, cuantos productos tienen {active_matter_name}?',
    'Dime todos los productos que contienen {active_matter_name}',
    'Luca, cuántos productos químicos contienen {active_matter_name}?',
    'Que productos con {active_matter_name} están registrados?',
    'Hola Luca, que fitosanitarios tienen {active_matter_name}?',
    'Luca, dame la lista de productos con {active_matter_name}',
    'Que insecticidas contienen {active_matter_name}?',
    'Hola, cuantos productos tienen {active_matter_name}?',
    'Luca, listado de químicos con {active_matter_name}',
    'Hola Luca, que productos tienen {active_matter_name}?',
    'Cuántos fitosanitarios contienen {active_matter_name}?',
    'Luca, que fungicidas llevan {active_matter_name}?',
    'Hola, dime los productos que contienen {active_matter_name}',
    'Que herbicidas tienen {active_matter_name}?',
    'Luca necesito saber qué productos contienen {active_matter_name}',
    'Productos disponibles con {active_matter_name} por favor',
    '¿Puedes decirme qué fungicidas llevan {active_matter_name}?',
    'Luca, necesito un listado de productos que contengan {active_matter_name}',
    '¿Me puedes indicar qué herbicidas incluyen {active_matter_name} en su composición?',
    'Oye Luca, ¿qué fitosanitarios hay con {active_matter_name}?',
    'Quiero información de todos los productos que llevan {active_matter_name}',
    'Lista los productos químicos que tienen {active_matter_name}'
  ],
  getChemicalProductsByClient: [
    'Muéstrame los agroquímicos registrados por {client_name}',
    'Necesito ver la lista de pesticidas que usa {client_name}',
    'Dame los productos químicos del cliente {client_name}',
    '¿Cuáles plaguicidas tiene anotados {client_name}?',
    'Quiero consultar los insecticidas y fungicidas que maneja {client_name}',
    'Listar todos los productos fitosanitarios disponibles para {client_name}',
    'Pásame los fungicidas registrados por {client_name}',
    'Enséñame los químicos agrícolas asociados a {client_name}',
    'Ver la lista completa de agroquímicos de {client_name}',
    'Dime qué tratamientos fitosanitarios utiliza {client_name}',
    '¿Puedes mostrarme los químicos agrícolas de {client_name}?',
    'Necesito revisar los pesticidas registrados por {client_name}',
    'Dame el inventario de productos químicos de {client_name}',
    'Lista los insecticidas que usa {client_name}',
    'Quiero ver qué fungicidas tiene registrados {client_name}',
    'Ver los productos químicos del cliente {client_name}',
    'Necesito los insecticidas y acaricidas para {client_name}',
    'Dame el inventario de químicos agrícolas de {client_name}',
    'Pásame la lista de plaguicidas para {client_name}',
    'Dime todos los productos fitosanitarios registrados por {client_name}',
    'Enséñame los agroquímicos que tiene {client_name}',
    '¿Puedes mostrarme los insecticidas de {client_name}?',
    'Quiero revisar los tratamientos químicos activos de {client_name}',
    'Listar los químicos agrícolas asociados a {client_name}',
    '¿Qué fungicidas y herbicidas tiene registrados {client_name}?',
    'Dame los pesticidas autorizados para {client_name}',
    'Enséñame los productos químicos que usa {client_name}',
    '¿Cuáles tratamientos fitosanitarios tiene actualmente {client_name}?',
    'Lista los fitosanitarios asociados al cliente {client_name}',
    'Muéstrame los agroquímicos disponibles para {client_name}'
  ],
  getFertilizers: [
    'muéstrame los fertilizantes',
    'quiero ver la lista de fertilizantes',
    'qué fertilizantes tiene el cliente {client_name}',
    'fertilizantes del cliente {client_name}',
    'lista de fertilizantes',
    'Muéstrame los abonos que tengo registrados ahora mismo.',
    '¿Qué fertilizantes tengo actualmente en la finca?',
    'Quiero consultar los productos fertilizantes que estoy usando.',
    'Lista los nutrientes agrícolas que tengo registrados.',
    '¿Me podrías mostrar qué abonos orgánicos tengo disponibles?',
    'Dime qué fertilizantes químicos tengo activos.',
    'Listar todos los nutrientes que estoy aplicando en los campos.',
    '¿Qué productos de abonado tengo en mis cultivos ahora mismo?',
    'Consultar los biofertilizantes registrados en mi cuenta.',
    'Mostrar los abonos minerales que utilizo.',
    'Ver la lista de abonos que tengo disponibles para aplicar.',
    'Dime los fertilizantes registrados por {client_name}.',
    'Quiero consultar los abonos que usa {client_name}.',
    '¿Puedes listar los productos fertilizantes que tiene {client_name}?',
    'Mostrar qué nutrientes agrícolas tiene registrados {client_name}.',
    'Listar todos los fertilizantes orgánicos registrados por {client_name}.',
    '¿Qué abonos minerales tiene actualmente {client_name}?',
    'Consultar productos de abonado disponibles para {client_name}.',
    'Muéstrame los biofertilizantes registrados por {client_name}.',
    'Listar nutrientes que tiene ahora mismo {client_name}.',
    'Kiero ver qué fertilizantes tengo en la finca.',
    'Mostrarme los productos de abono que utilizo ahora.',
    '¿Qué tipos de fertilizante tengo registrados?',
    'Dime los abonos que tengo en uso actualmente.',
    'Consulta rápida de nutrientes agrícolas que utilizo en mis parcelas.',
    '¿Podrías mostrarme qué biofertilizantes tengo disponibles?',
    'Listame los fertilizantes químicos que estoy aplicando ahora mismo.',
    'Quiero consultar todos los productos fertilizantes que utilizo en la finca.',
    'Ver la lista completa de abonos registrados en mi cuenta.',
    'Muéstrame los fertilizantes que tengo activos ahora mismo en mis cultivos.',
    'Listar fertilizantes de {client_name}.',
    'Listar fertilizantes de {client_name}.',
    'Listar fertilizantes de {client_name}.',
    'Listar fertilizantes de {client_name}.',
    'Listar fertilizantes de {client_name}.',
    'Listar fertilizantes de {client_name}.',
    'Oye luca, dime todos los productos quimicos',
    'Oye luca, dime todos los productos quimicos de {client_name}.',
    'Dime los fertilizantes de {client_name}',
    'Dime los fertilizantes de {client_name}',
    'Dime los fertilizantes de {client_name}',
    'dame los fertilizantes de {client_name}',
    'lista los fertilizantes de {client_name}',
    'Dime los fertilizantes de {client_name}',
    'dime los fertilizantes de {client_name}'
  ],
  getLastPrice: [
    'Hola Luca, cuál es el último precio de {search_query}?',
    'Luca, dime el precio más reciente del {search_query}',
    'cuánto fue lo último que pagué por {search_query}?',
    'cuál fue el último precio registrado del {search_query}?',
    'dime el precio actualizado del {search_query}',
    'Luca, ¿cuánto costó por última vez el {search_query}?',
    'cuál es el precio más reciente que tengo del {search_query}?',
    'quiero saber el último valor de venta de {search_query}',
    'Luca, ¿a cómo estuvo el {search_query} en la última compra?',
    '¿A cómo he comprado la última vez {search_query}?',
    'Muéstrame el precio más reciente del producto {search_query}.',
    'Quiero consultar el valor actual de la {search_query}.',
    'Dime cuál es el coste registrado de {search_query}.',
    '¿Puedes mostrar el precio actualizado de {search_query}?',
    'Listar el último importe registrado para {search_query}.',
    'Ver el último coste anotado del {search_query}.',
    'Dime el precio reciente del producto {search_query}.',
    '¿Cuál es la última tarifa del {search_query}?',
    'Mostrar el importe más reciente registrado para {search_query}.',
    'Kiero ver a cuánto está actualmente la {search_query}.',
    '¿A qué valor tengo registrado el producto {search_query}?',
    'Dime el importe reciente que pagó {nombre_usuario_cliente} por {search_query}.',
    '¿Cuál es el precio actualizado de {search_query} para {nombre_usuario_cliente}?',
    'Muéstrame el valor más reciente de la {search_query} registrada por {nombre_usuario_cliente}.',
    'Consultar coste del {search_query} para {nombre_usuario_cliente}.',
    'Listar el importe registrado del producto {search_query} para {nombre_usuario_cliente}.',
    'Ver tarifa actual del {search_query} que tiene {nombre_usuario_cliente}.',
    '¿Qué valor tiene anotado {nombre_usuario_cliente} para el producto {search_query}?',
    'Dime el coste más reciente de {search_query} para {nombre_usuario_cliente}.',
    '¿Puedes mostrarme la tarifa actual del {search_query}?',
    'Listar precio reciente del producto {search_query} para mis parcelas.',
    'Muéstrame el importe registrado del {search_query} en mi cuenta.',
    'Consultar el coste actualizado de la {search_query}.',
    '¿A cuánto he comprado la última vez {search_query} en mis fincas?',
    'Ver precio reciente anotado para el producto {search_query}.',
    'Dime el valor actual que tengo del {search_query}.',
    'Listar tarifa más reciente para el producto {search_query}.',
    '¿Qué importe tengo registrado para {search_query}?',
    'Mostrar coste actualizado del {search_query}.',
    'Hola Luca, cuál es el último precio del {search_query} para el cliente {nombre_usuario_cliente}',
    'Hola Luca, cuál es el último precio del {search_query} para el cliente {nombre_usuario_cliente}',
    'Hola Luca, cuál es el último precio de {search_query} para el cliente {nombre_usuario_cliente}',
    'Hola Luca, cuál es el último precio de {search_query} para el cliente {nombre_usuario_cliente}'
  ],
  getManufacturerProducts: [
    'Hola Luca, dime que fertilizantes tiene {manufacturer_name}',
    'Hola Luca, que clasificación de fertilizantes tiene {manufacturer_name}?',
    'Hola Luca! Que productos de D-Coder tiene {manufacturer_name}?',
    'Hola Luca, cuántos fertilizantes tiene {manufacturer_name}',
    'Luca, muéstrame la clasificación de productos químicos de {manufacturer_name}',
    'Qué gamas de fertilizantes ofrece {manufacturer_name}',
    'Luca, dime los fertilizantes que tiene {manufacturer_name}',
    'Quiero saber qué fitosanitarios tiene {manufacturer_name}',
    'Dime las gamas de químicos que vende {manufacturer_name}',
    'Hola Luca, listado de fertilizantes de {manufacturer_name} por favor',
    '¿Cuántos productos químicos tiene {manufacturer_name} en la app?',
    '¿Cuántos productos químicos tiene {manufacturer_name} en la app?',
    'Muestra la clasificación de fertilizantes de {manufacturer_name}',
    'Hola, dime todos los químicos que ofrece {manufacturer_name}',
    'Luca, qué gamas de fitosanitarios tiene {manufacturer_name}?',
    'Quiero saber las gamas de fertilizantes de {manufacturer_name}',
    'Hola Luca, cuántos fitosanitarios vende {manufacturer_name}',
    'Dime todos los fertilizantes de {manufacturer_name}',
    'Luca, clasificación de fertilizantes de {manufacturer_name}',
    'Muéstrame cuántos productos químicos tiene {manufacturer_name}',
    'Qué gamas de fertilizantes hay en {manufacturer_name}?',
    'Hola Luca, lista de fitosanitarios de {manufacturer_name}',
    'Clasificación de productos químicos de {manufacturer_name} por favor',
    'Cuántos fertilizantes tiene {manufacturer_name} en total?'
  ],
  getPlannedCampaignsHistory: [
    'Muéstrame el historial de campañas de la granja {farm_name}',
    'Muestra el historial de campañas de la granja {farm_name}',
    'Muestra el historial de campañas de la granja {farm_name} para el campo {field_name}',
    'Quiero ver el historial de campañas de {client_name} en la granja {farm_name}',
    'Dame el historial del campo {field_name} en la granja {farm_name}',
    'Dame el historial del campo {field_name} en la granja {farm_name}',
    'Historial de campañas para {farm_name}',
    'Muestra las campañas pasadas de {farm_name}',
    'Quiero el historial de campañas de {client_name}',
    'Muéstrame el historial de campañas',
    'Necesito saber las campañas pasadas del campo {field_name}',
    'Dame el historial del campo {field_name} de la granja {farm_name}',
    'Quiero ver las campañas anteriores del cliente {client_name} en {farm_name}',
    'Consulta el historial de campañas de {client_name} para el campo {field_name} en {farm_name}',
    'Historial de campañas del campo {field_name} de la granja {farm_name}',
    '¿Cuál es el historial de campañas en {farm_name} campo {field_name}?',
    'Muéstrame las campañas anteriores en la granja {farm_name} para el campo {field_name}',
    'Quiero conocer el historial de campañas de {farm_name}'
  ],
  getPriceVariation: [
    'Hola Luca, cuál ha sido la variación del precio del {search_query}?',
    'Luca, dime cuánto ha variado el precio del {search_query}',
    '¿Qué tanta variación ha tenido el producto {search_query}?',
    'quiero saber si el precio del {search_query} ha subido o bajado',
    'cuánto ha cambiado el valor del {search_query} en los últimos años?',
    'Luca, ¿cuánto ha aumentado o disminuido el precio del {search_query}?',
    '¿Cuál ha sido el cambio reciente del precio del {search_query}?',
    'Muéstrame cómo ha evolucionado el precio de la {search_query}.',
    'Quiero consultar las variaciones recientes en el precio del {search_query}.',
    'Dime cómo ha fluctuado el precio del {search_query}.',
    '¿Puedes mostrarme la evolución del coste de {search_query}?',
    'Listar cambios de precio registrados para el producto {search_query}.',
    'Ver cómo ha cambiado últimamente el importe del {search_query}.',
    'Consultar el movimiento reciente en el valor del {search_query}.',
    'Muéstrame la tendencia del precio para {search_query}.',
    '¿Qué modificaciones ha tenido el precio del {search_query}?',
    'Mostrar evolución reciente del importe del {search_query}.',
    'Dime si ha habido variación en el coste de la {search_query}.',
    '¿Cómo ha fluctuado últimamente el precio del {search_query}?',
    'Consultar cambios recientes en la tarifa del {search_query}.',
    'Muéstrame la variación reciente del coste del {search_query}.',
    '¿Ha habido cambios últimamente en el valor de la {search_query}?',
    'Quiero ver cómo ha evolucionado el precio del {search_query}.',
    'Mostrar la fluctuación reciente en el precio del {search_query}.',
    'Kiero saber los movimientos del precio del {search_query}.',
    '¿Cuál es la tendencia del importe del producto {search_query}?',
    'Ver modificaciones recientes en el coste del {search_query}.',
    'Listar evolución del precio del {search_query} para {client_name}.',
    'Muéstrame cómo ha variado el precio de la {search_query} para {client_name}.',
    'Dime el cambio reciente en la tarifa de {search_query} registrada por {client_name}.',
    '¿Cuál ha sido la fluctuación del precio del producto {search_query} para {client_name}?',
    'Consultar evolución del importe del {search_query} asociado a {client_name}.',
    'Mostrar variaciones recientes del coste del {search_query} para {client_name}.',
    '¿Puedes decirme cómo ha cambiado el valor de {search_query} para {client_name}?',
    'Listar modificaciones recientes en el precio de la {search_query} registradas por {client_name}.',
    'Ver evolución del precio del {search_query} en la finca de {client_name}.',
    'Hola Luca, cuál ha sido la variación del precio del {search_query}?'
  ],
  getSeedsNeeded: [
    'Hola Luca, ¿cuántos kilos de semillas necesito?',
    '¿Qué cantidad de semillas se necesita para esta campaña?',
    'Luca, dime cuántos kg de semillas hacen falta por cultivo',
    '¿Cuánta semilla debo usar para cada cultivo?',
    '¿Qué dosis debo aplicar para cada variedad?'
  ],
  goodbye: [
    'adiós',
    'chao',
    'hasta luego'
  ],
  greet: [
    'hola',
    'buenos días',
    'hey',
    'buenas tardes',
    'buenas noches',
    'saludos',
    'qué tal',
    'cómo estás',
    'hola Luca',
    'buenos días Luca',
    'oye Luca',
    'hey Luca',
    'ey Luca',
    'Luca, hola',
    'Luca, ¿qué tal?',
    'Luca, buenos días',
    'hola, ¿cómo vas?',
    'un saludo',
    'qué hay',
    'qué pasa',
    'Luca'
  ],
  reportFinishedWork: [
    'Quiero reportar un trabajo finalizado',
    'Reportar trabajo terminado',
    'Reportar horas trabajadas',
    'Reportar el trabajo {work_id} con {worked_hours} horas',
    'Reportar {work_id} y {worked_hours} horas',
    'Reporta el trabajo con id {work_id}',
    'Reportar siembra: trabajo {work_id} con {worked_hours} horas, dosis aplicada {applied_dose}',
    'Reportar fitosanitarios: {work_id}, {worked_hours} horas, dosis general {general_dose} L/ha, químicos "Glifosato:2.5, 2,4-D:1.8"',
    'Reporte de cosecha {work_id} con {worked_hours} horas y {amount_harvested} kg',
    'Quiero reportar laboreo {work_id} horas {worked_hours} profundidad {depth} cm',
    'Reportar fertilización {work_id} {worked_hours} horas, dosis {applied_dose} kg/ha',
    'Reportar con máquina "Tractor John Deere" y combustible {fuel_used} L',
    'Necesito reportar un trabajo (me falta el id)',
    'Quiero reportar un trabajo (me faltan horas)',
    'Reportar un trabajo finalizado (faltan id y horas)',
    'Reportar trabajo {work_id} sin horas (falta workedHours)',
    'Reportar horas {worked_hours} del trabajo (falta workId)'
  ],
  requestOtp: [
    'enviar otp',
    'necesito un código de verificación',
    'mándame el código',
    'quiero verificar mi número',
    'envíame un OTP',
    'puedes mandarme el código?',
    'envía el otp a mi número',
    'mándalo a mi WhatsApp',
    'quiero recibir el código',
    'verifica mi número',
    'necesito que me llegue el otp',
    'mándame el código a mi WhatsApp',
    'envíame el código, por favor',
    'me puedes mandar el otp?',
    'necesito un código para verificar',
    'quiero verificar mi cuenta',
    'envíalo a mi WhatsApp',
    'mándame ese código',
    'puedes enviar el código?',
    'código, por favor',
    'necesito un OTP para entrar',
    'manda el código a mi celular',
    'envía la verificación',
    'quiero el código en mi teléfono registrado',
    'mándame un código para acceder'
  ],
  searchProducts: [
    'busca {search_query}',
    'quiero buscar productos que contengan {search_query}',
    'búscame {search_query} en los productos del cliente {client_name}',
    'buscar {search_query}',
    'encuentra {search_query} para el cliente {client_name}',
    'hay algo de {search_query}?',
    'busca {search_query} para el cliente {client_name}',
    '¿Qué tipos tengo registrados de {search_query}?',
    'Muéstrame todas las clases del cultivo {search_query}.',
    'Quiero ver las subespecies que tengo actualmente de {search_query}.',
    '¿Me podrías mostrar las líneas que tengo registradas del {search_query}?',
    'Consultar las variedades que tengo del {search_query}.',
    'Dime qué tipos de {search_query} tengo activos ahora.',
    'Mostrar las clases de {search_query} que tengo en mis parcelas.',
    'Ver las formas distintas del {search_query} registradas.',
    '¿Qué variantes tengo anotadas del {search_query}?',
    'Lista las variedades agrícolas del cultivo {search_query}.',
    'Dime las variedades de {search_query} registradas por el cliente {client_name}.',
    '¿Qué clases de {search_query} tiene el cliente {client_name}?',
    'Muéstrame las variedades de {search_query} que tiene registradas {client_name}.',
    'Consultar subtipos del cultivo {search_query} registrados por {client_name}.'
  ],
  searchProductsCrops: [
    '¿Existe el cultivo {search_query} registrado?',
    'Muéstrame todas las plantaciones con el nombre {search_query}.',
    'Quiero ver los cultivos que coincidan con {search_query}.',
    '¿Me podrías decir si tengo alguna siembra llamada {search_query}?',
    'Listar los cultivos que contengan la palabra {search_query}.',
    'Dime si hay alguna plantación registrada como {search_query}.',
    '¿Qué especies agrícolas coinciden con {search_query}?',
    'Mostrarme si tengo algún cultivo con nombre {search_query}.',
    'Consultar las siembras registradas con la palabra {search_query}.',
    'Kiero saber si existe alguna especie vegetal con el nombre {search_query}.',
    '¿Puedes listar las plantaciones con nombre {search_query}?',
    'Dime si tengo registrados cultivos como {search_query}.',
    'Ver si {client_name} tiene algún cultivo llamado {search_query}.',
    '¿Tiene {client_name} alguna plantación con el nombre {search_query}?',
    'Mostrar los cultivos de {client_name} que contengan {search_query}.',
    'Consultar si {client_name} ha registrado alguna siembra como {search_query}.',
    'Muéstrame los cultivos que {client_name} tiene con el nombre {search_query}.',
    'Listar plantaciones de {client_name} que se llamen {search_query}.',
    '¿Qué especies vegetales tiene {client_name} llamadas {search_query}?',
    'Dime si existe alguna plantación llamada {search_query} para {client_name}.',
    '¿Me muestras si {client_name} tiene algún cultivo con nombre {search_query}?',
    'Quiero consultar las siembras con el nombre {search_query} asociadas a {client_name}.',
    'Mostrarme especies agrícolas registradas por {client_name} que contengan {search_query}.',
    'Dime qué cultivos con el nombre {search_query} tiene {client_name}.',
    'Consultar las plantaciones llamadas {search_query} que tiene {client_name}.',
    '¿Puedes listar si {client_name} tiene registrado el cultivo {search_query}?',
    'Listar especies vegetales que coincidan con {search_query}.',
    'Ver plantaciones con nombre {search_query} registradas por {client_name}.',
    'Muéstrame los cultivos registrados con la palabra {search_query}.',
    'Dime si {client_name} tiene alguna siembra llamada {search_query}.',
    '¿qué cultivos de {search_query} tiene el cliente {client_name}?'
  ],
  searchProductsFertilizers: [
    'busca {search_query}',
    'quiero buscar productos que contengan {search_query}',
    'encuentra {search_query} para el cliente {client_name}',
    'busca el fertilizante {search_query}',
    'necesito encontrar abono {search_query}',
    'muéstrame fertilizante {search_query} de hierro',
    '¿hay fertilizante {search_query} para cítricos?',
    'busca nutriente {search_query} para el cliente {client_name}',
    'quiero ver {search_query}',
    'encuentra abono {search_query} líquido',
    '¿qué tipos de fertilizante {search_query} de calcio tenemos?',
    'lista los nutrientes {search_query} para {client_name}',
    'buscar {search_query}',
    'consulta {search_query}',
    'muéstrame  {search_query} para tomate',
    '¿tenemos {search_query}?',
    'necesito {search_query} para {client_name}',
    'busca micronutrientes {search_query}',
    'quiero ver fertilizante {search_query}',
    '¿hay estimulante {search_query} disponible?',
    'consulta los fertilizantes {search_query} de {client_name}',
    'busca abono {search_query} con aminoácidos',
    'quiero información sobre {search_query}',
    'Hola Luca,existe el fertilizante {search_query}?',
    'Hola Luca existe el fertilizante {search_query}?',
    'dime los fertilizantes de {client_name}'
  ]
} as const;

export const INTENTS = Object.fromEntries(
  Object.entries(INTENTS_TEMPLATES).map(([k, arr]) => [k, materializeAll(arr, VARS)])
);

// Lista de cultivos disponibles para selección aleatoria
export const CROPS_POOL = [
  { crop_name: 'trigo', variety_name: 'Chamorro', destination: 'pienso', brand: 'GrainMaster' },
  { crop_name: 'maíz', variety_name: 'p 8660', destination: 'consumo', brand: 'SeedTech' },
  { crop_name: 'cebada', variety_name: 'Golden', destination: 'pienso', brand: 'HarvestPlus' },
  { crop_name: 'avena', variety_name: 'Premium', destination: 'consumo', brand: 'FarmSelect' },
  { crop_name: 'girasol', variety_name: 'Solaris', destination: 'consumo', brand: 'SunFields' },
  { crop_name: 'tomate', variety_name: 'Raf', destination: 'consumo', brand: 'VeggieTop' }
];

export function randomCrop(): typeof CROPS_POOL[number] {
  return CROPS_POOL[Math.floor(Math.random() * CROPS_POOL.length)];
}

export const KEYWORD_RULES: Array<{
  pattern: RegExp;
  action: { type: 'REPLY'; reply: string } | { type: 'END_OK' } | { type: 'END_ERR' } | { type: 'RETRY_EXISTS' };
  note: string;
  priority?: number;
  intents?: string[]; // Lista de intents donde aplica esta regla. Si está vacío o undefined, aplica a todos
}> = [
  // Opciones - se procesará con extractFirstOption en flow.ts (PRIORIDAD 1 - MÁXIMA)
  { pattern: /opciones:/i, action: { type: 'REPLY', reply: '__EXTRACT_FIRST_OPTION__' }, note: 'Lista de opciones detectada', priority: 1 },
  
  // Ya existe - ahora es un finalizador exitoso (PRIORIDAD 2)
  { pattern: /y[aá]\s+(exist[eé]|exist|existe)/i, action: { type: 'END_OK' }, note: 'Elemento ya existe - finalizar como éxito', priority: 2 },
  
  // Finalizadores específicos (prioridad 2)
  { pattern: /fertilizante creado exitosamente/i, action: { type: 'END_OK' }, note: 'Fertilizante creado exitosamente', priority: 2 },
  { pattern: /cultivo creado exitosamente/i, action: { type: 'END_OK' }, note: 'Cultivo creado exitosamente', priority: 2 },
  { pattern: /campaña (cread[oa]) exitosamente/i, action: { type: 'END_OK' }, note: 'Campaña creada exitosamente', priority: 2 },
  { pattern: /(fitosanitario|producto químico|producto) creado exitosamente/i, action: { type: 'END_OK' }, note: 'Fitosanitario/Producto creado exitosamente', priority: 2 },
  { pattern: /(precio (asignado|actualizado|registrado)|asigno un precio|precio fijado)/i, action: { type: 'END_OK' }, note: 'Precio asignado/actualizado exitosamente', priority: 2 },
  
  // Finalizadores de éxito
  { pattern: /creado correctamente|registrado correctamente|guardado correctamente|planificado correctamente|asignado correctamente/i, action: { type: 'END_OK' }, note: 'Creación exitosa', priority: 2 },
  { pattern: /operación completada|proceso finalizado|todo listo|completado exitosamente/i, action: { type: 'END_OK' }, note: 'Operación exitosa', priority: 2 },
  { pattern: /reporte enviado|trabajo reportado/i, action: { type: 'END_OK' }, note: 'Reporte exitoso', priority: 2 },
  { pattern: /exito|exitoso|exitosa|exitosos|exitosas/i, action: { type: 'END_OK' }, note: 'Éxito detectado (cualquier variante)', priority: 2 },
  
  // Finalizadores para consultas GET (devuelven información sin acción adicional)
  { pattern: /[aáä]ct[uúü][aá]lm[eé]nt[eé] t[ií][eé]n[eé]s \d+ cultivos?/i, action: { type: 'END_OK' }, note: 'Lista de cultivos completada', priority: 2 },
  { pattern: /tienes \d+ fertilizante/i, action: { type: 'END_OK' }, note: 'Lista de fertilizantes completada', priority: 2 },
  { pattern: /estos son los (\d+ )?productos/i, action: { type: 'END_OK' }, note: 'Lista de productos completada', priority: 2 },
  { pattern: /aqu[ií] est[áa]n?:?\s*\.?\s*\n.*(?:cultivo|fertilizante|producto|trabajo|campaña)/i, action: { type: 'END_OK' }, note: 'Lista de resultados mostrada', priority: 2 },
  { pattern: /n[oó] h[aá]y \(c[uúü]lt[ií]v[oó]s\|f[eé]rt[ií]l[ií]z[aá]nt[eé]s\|pr[oó]d[uúü]ct[oó]s\|tr[aá]b[aá]j[oó]s\|c[aá]mp[aá]ñ[aá]s\) d[ií]sp[oó]n[ií]bl[eé]s/i, action: { type: 'END_ERR' }, note: 'Consulta sin resultados', priority: 2 },
  { pattern: /no se encontr[óo] ningún/i, action: { type: 'END_OK' }, note: 'Consulta sin resultados', priority: 2 },
  { pattern: /el [úu]ltimo (precio|trabajo|campaña)/i, action: { type: 'END_OK' }, note: 'Consulta de último registro', priority: 2 },
  { pattern: /la distribuci[óo]n (de cultivos )?es:/i, action: { type: 'END_OK' }, note: 'Distribución mostrada', priority: 2 },
  { pattern: /trabajos pendientes.*:/i, action: { type: 'END_OK' }, note: 'Lista de pendientes', priority: 2 },
  { pattern: /h[ií]st[oó]r[ií][aá]l d[eé] c[aá]mp[aá]ñ[aá]s/i, action: { type: 'END_OK' }, note: 'Historial mostrado', priority: 2, intents: ['getPlannedCampaignsHistory'] },
  { pattern: /variaci[óo]n de precio/i, action: { type: 'END_OK' }, note: 'Variación mostrada', priority: 2 },
  
  // Finalizadores de error
  { pattern: /error|fallo|problema|no se pudo|no se encontró|no existe|inválido/i, action: { type: 'END_ERR' }, note: 'Error detectado', priority: 2 },
  
  // Campos de Cultivo
  { pattern: /\bnombre\s+de\s+la\s+variedad/i, action: { type: 'REPLY', reply: '{variety_name}' }, note: 'Pide variedad (usado en: createCrop, createPlannedCampaign, createPlannedWork)', priority: 3 },
  { pattern: /\bvariedad(\s+del\s+cultivo)?[\s]*[?:]/i, action: { type: 'REPLY', reply: '{variety_name}' }, note: 'Pide variedad (usado en: createCrop, createPlannedCampaign, createPlannedWork)', priority: 3 },
  { pattern: /\bnombre\s+del\s+cultivo/i, action: { type: 'REPLY', reply: '{crop_name}' }, note: 'Pide nombre cultivo (usado en: createCrop, createPlannedCampaign, createPlannedWork)', priority: 3 },
  { pattern: /\bqu[ée]\s+cultivo/i, action: { type: 'REPLY', reply: '{crop_name}' }, note: 'Pide qué cultivo (usado en: createCrop, createPlannedCampaign, createPlannedWork)', priority: 3 },
  { pattern: /\bdestino(\s+del\s+cultivo)?/i, action: { type: 'REPLY', reply: '{destination}' }, note: 'Pide destino (usado en: createCrop)', priority: 3 },
  { pattern: /\bmarca(\s+del\s+cultivo)?/i, action: { type: 'REPLY', reply: '{brand}' }, note: 'Pide marca (usado en: createCrop, createChemicalProduct)', priority: 3 },
  
  // Campos de Cliente
  { pattern: /\bnombre\s+del\s+cliente/i, action: { type: 'REPLY', reply: '{client}' }, note: 'Pide cliente (usado en: createCrop, createChemicalProduct, getChemicalProductsByClient, searchProducts)', priority: 3 },
  { pattern: /\bpara\s+qu[ée]\s+cliente/i, action: { type: 'REPLY', reply: '{client}' }, note: 'Pide cliente (usado en: createCrop, createChemicalProduct, getChemicalProductsByClient, searchProducts)', priority: 3 },
  { pattern: /cl[ií][eé]nt[eé]/i, action: { type: 'REPLY', reply: '{client}' }, note: 'Pide cliente (usado en: createCrop, createChemicalProduct, getChemicalProductsByClient, searchProducts)', priority: 3 },
  { pattern: /\bnombre\s+de\s+usuario\s+del\s+cliente/i, action: { type: 'REPLY', reply: '{nombre_usuario_cliente}' }, note: 'Pide usuario cliente (usado en: requestOtp)', priority: 3 },
  { pattern: /\busuario\s+del\s+cliente/i, action: { type: 'REPLY', reply: '{nombre_usuario_cliente}' }, note: 'Pide usuario cliente (usado en: requestOtp)', priority: 3 },
  
  // Campos de Fertilizante
  { pattern: /\bnombre\s+del\s+fertilizante/i, action: { type: 'REPLY', reply: '{fertilizer_name}' }, note: 'Pide fertilizante (usado en: createFertilizer, filterFertilizers, searchProductsFertilizers)', priority: 3 },
  { pattern: /f[eé]rt[ií]l[ií]z[aá]nt[eé]/i, action: { type: 'REPLY', reply: '{fertilizer_name}' }, note: 'Pide fertilizante (usado en: createFertilizer, filterFertilizers, searchProductsFertilizers)', priority: 3 },
  { pattern: /\btipo\s+de\s+fertilizante/i, action: { type: 'REPLY', reply: '{type_fertilizer}' }, note: 'Pide tipo fertilizante (usado en: createFertilizer, filterFertilizers)', priority: 3 },
  { pattern: /c[oó]mp[oó]s[ií]c[ií][oó]n/i, action: { type: 'REPLY', reply: '{composition}' }, note: 'Pide composición (usado en: createFertilizer)', priority: 3 },
  { pattern: /\bforma(\s+del\s+fertilizante)?/i, action: { type: 'REPLY', reply: '{form_type}' }, note: 'Pide forma (usado en: createFertilizer, filterFertilizers)', priority: 3 },
  { pattern: /\bnivel\s+de\s+nitr[oó]geno/i, action: { type: 'REPLY', reply: '{nitrogen_level}' }, note: 'Pide nitrógeno (usado en: createFertilizer, filterFertilizers)', priority: 3 },
  
  // Campos de Producto Químico
  { pattern: /\bnombre\s+del\s+fabricante/i, action: { type: 'REPLY', reply: '{manufacturer_name}' }, note: 'Pide fabricante (usado en: createChemicalProduct, createFertilizer, getManufacturerProducts)', priority: 3 },
  { pattern: /f[aá]br[ií]c[aá]nt[eé]/i, action: { type: 'REPLY', reply: '{manufacturer_name}' }, note: 'Pide fabricante (usado en: createChemicalProduct, createFertilizer, getManufacturerProducts)', priority: 3 },
  { pattern: /\bnombre\s+del\s+producto\s+qu[ií]mico/i, action: { type: 'REPLY', reply: '{chemical_product_name}' }, note: 'Pide producto químico (usado en: createChemicalProduct, getActiveMatterChemicalProducts)', priority: 3 },
  { pattern: /\bproducto\s+qu[ií]mico/i, action: { type: 'REPLY', reply: '{chemical_product_name}' }, note: 'Pide producto químico (usado en: createChemicalProduct, getActiveMatterChemicalProducts)', priority: 3 },
  { pattern: /\bmateria\s+activa/i, action: { type: 'REPLY', reply: '{active_matter_name}' }, note: 'Pide materia activa (usado en: getActiveMatterChemicalProducts)', priority: 3 },
  { pattern: /\bprincipio\s+activo/i, action: { type: 'REPLY', reply: '{active_matter_name}' }, note: 'Pide principio activo (usado en: getActiveMatterChemicalProducts)', priority: 3 },
  { pattern: /\bplaga\s+objetivo/i, action: { type: 'REPLY', reply: '{target_pest}' }, note: 'Pide plaga objetivo (usado en: createChemicalProduct)', priority: 3 },
  { pattern: /pl[aá]g[aá]/i, action: { type: 'REPLY', reply: '{target_pest}' }, note: 'Pide plaga (usado en: createChemicalProduct)', priority: 3 },
  { pattern: /\bmodo\s+de\s+acci[oó]n/i, action: { type: 'REPLY', reply: '{mode_of_action}' }, note: 'Pide modo acción (usado en: createChemicalProduct)', priority: 3 },
  
  // Campos de Granja/Campo
  { pattern: /\bnombre\s+de\s+la\s+granja/i, action: { type: 'REPLY', reply: '{farm_name}' }, note: 'Pide granja (usado en: createPlannedCampaign, createPlannedWork, reportFinishedWork)', priority: 3 },
  { pattern: /gr[aá]nj[aá]/i, action: { type: 'REPLY', reply: '{farm_name}' }, note: 'Pide granja (usado en: createPlannedCampaign, createPlannedWork, reportFinishedWork)', priority: 3 },
  { pattern: /[eé]xpl[oó]t[aá]c[ií][oó]n/i, action: { type: 'REPLY', reply: '{farm_name}' }, note: 'Pide explotación (usado en: createPlannedCampaign, createPlannedWork, reportFinishedWork)', priority: 3 },
  { pattern: /\bqu[ée]\s+granja/i, action: { type: 'REPLY', reply: '{farm_name}' }, note: 'Pide qué granja (usado en: createPlannedCampaign, createPlannedWork, reportFinishedWork)', priority: 3 },
  { pattern: /\bnombre\s+del\s+campo/i, action: { type: 'REPLY', reply: '{field_name}' }, note: 'Pide campo (usado en: createPlannedCampaign, createPlannedWork, reportFinishedWork)', priority: 3 },
  { pattern: /c[aá]mp[oó]/i, action: { type: 'REPLY', reply: '{field_name}' }, note: 'Pide campo (usado en: createPlannedCampaign, createPlannedWork, reportFinishedWork)', priority: 3 },
  { pattern: /p[aá]rc[eé]l[aá]/i, action: { type: 'REPLY', reply: '{field_name}' }, note: 'Pide parcela (usado en: createPlannedCampaign, createPlannedWork, reportFinishedWork)', priority: 3 },
  { pattern: /\bqu[ée]\s+campo/i, action: { type: 'REPLY', reply: '{field_name}' }, note: 'Pide qué campo (usado en: createPlannedCampaign, createPlannedWork, reportFinishedWork)', priority: 3 },
  
  // Campos de Trabajo
  { pattern: /\btipo\s+de\s+trabajo/i, action: { type: 'REPLY', reply: '{type_work}' }, note: 'Pide tipo trabajo (usado en: createPlannedWork, reportFinishedWork)', priority: 3 },
  { pattern: /\bID\s+del\s+trabajo/i, action: { type: 'REPLY', reply: '{work_id}' }, note: 'Pide ID trabajo (usado en: reportFinishedWork)', priority: 3 },
  { pattern: /\bhoras\s+trabajadas/i, action: { type: 'REPLY', reply: '{worked_hours}' }, note: 'Pide horas (usado en: reportFinishedWork)', priority: 3 },
  { pattern: /\bdosis\s+aplicada/i, action: { type: 'REPLY', reply: '{applied_dose}' }, note: 'Pide dosis aplicada (usado en: reportFinishedWork)', priority: 3 },
  { pattern: /\bdosis\s+general/i, action: { type: 'REPLY', reply: '{general_dose}' }, note: 'Pide dosis general (usado en: createPlannedWork)', priority: 3 },
  { pattern: /\bcantidad\s+cosechada/i, action: { type: 'REPLY', reply: '{amount_harvested}' }, note: 'Pide cantidad cosechada (usado en: reportFinishedWork)', priority: 3 },
  { pattern: /Profundidad/i, action: { type: 'REPLY', reply: '{depth}' }, note: 'Pide profundidad (usado en: createPlannedWork, reportFinishedWork)', priority: 3 },
  { pattern: /Combustible usado/i, action: { type: 'REPLY', reply: '{fuel_used}' }, note: 'Pide combustible (usado en: reportFinishedWork)', priority: 3 },
  
  // Campos de Precio
  { pattern: /Precio/i, action: { type: 'REPLY', reply: '{price}' }, note: 'Pide precio (usado en: assignPriceProduct, createChemicalProduct, getMinPrice, getLastPrice, getPriceVariation)', priority: 3 },
  { pattern: /Fecha del precio/i, action: { type: 'REPLY', reply: '{price_date}' }, note: 'Pide fecha precio (usado en: assignPriceProduct)', priority: 3 },
  { pattern: /Nombre del producto/i, action: { type: 'REPLY', reply: '{product_name}' }, note: 'Pide nombre producto (usado en: assignPriceProduct, getMinPrice, getLastPrice, getPriceVariation, getSeedsNeeded)', priority: 3 },
  
  // Búsquedas
  { pattern: /Búsqueda/i, action: { type: 'REPLY', reply: '{search_query}' }, note: 'Pide búsqueda (usado en: searchProducts, searchProductsCrops, searchProductsFertilizers)', priority: 3 },
  { pattern: /Qué producto buscar/i, action: { type: 'REPLY', reply: '{search_query}' }, note: 'Pide producto búsqueda (usado en: searchProducts, searchProductsCrops, searchProductsFertilizers)', priority: 3 },
  
  
  { pattern: /T[oó]t[aá]l:/i, action: { type: 'END_OK' }, note: 'ok', priority: 2, intents: ['checkUnplannedFields', 'getPlannedCampaignsHistory'] },
  { pattern: /[ií]ngr[eé]s[aá] l[aá] f[eé]ch[aá]/i, action: { type: 'REPLY', reply: '2026-10-15' }, note: 'fecha', priority: 3 },
  { pattern: /H[eé]ch[oó]:/i, action: { type: 'END_OK' }, note: 'ok', priority: 2 },
  { pattern: /pl[aá]n[ií]f[ií]c[aá]d[aá] [eé]n d[eé]c[ií]m[aá]l/i, action: { type: 'REPLY', reply: '180.0' }, note: 'd', priority: 3 },
  { pattern: /[ií]ngr[eé]s[aá] l[aá] h[oó]r[aá]/i, action: { type: 'REPLY', reply: '14:30' }, note: 'yy', priority: 3 },
  { pattern: /N[oó]mbr[eé] d[eé]l [oó]p[eé]r[aá]d[oó]r/i, action: { type: 'REPLY', reply: 'Juan Andrés Menton' }, note: 'jose', priority: 3 },
  { pattern: /D[oó]s[ií]s d[eé]l c[uúü]lt[ií]v[oó]/i, action: { type: 'REPLY', reply: '120.0' }, note: 'jj', priority: 3 },
  { pattern: /[aá]ct[uúü][aá]lm[eé]nt[eé] t[ií][eé]n[eé]s/i, action: { type: 'END_OK' }, note: 'ok', priority: 2, intents: ['filterFertilizers', 'getActiveMatterChemicalProducts', 'getChemicalProducts', 'getChemicalProductsByClient', 'getCropDistribution', 'getCrops', 'getFertilizers', 'getLastPrice', 'getLastWork', 'getManufacturerProducts', 'getMinPrice', 'getPendingWorks', 'getPlannedCampaignsHistory', 'getPriceVariation', 'getSeedsNeeded', 'searchProducts', 'searchProductsCrops', 'searchProductsFertilizers'] },
  { pattern: /L[oó] s[ií][eé]nt[oó], n[oó] l[oó]gré [eé]nc[oó]ntr[aá]r l[aá] [ií]nf[oó]rm[aá]c[ií]ón q[uúü][eé] b[uúü]sc[aá]s/i, action: { type: 'END_ERR' }, note: 'err', priority: 2 },
  { pattern: /¡H[oó]l[aá]!, l[oó]s pr[oó]d[uúü]ct[oó]\(s\) q[uúü][eé] t[ií][eé]n[eé]s cr[eé][aá]d[oó]s s[oó]n/i, action: { type: 'END_OK' }, note: 'ok', priority: 2, intents: ['getChemicalProducts', 'getChemicalProductsByClient'] },
  { pattern: /n[oó] l[oó]gré [eé]nc[oó]ntr[aá]r/i, action: { type: 'END_ERR' }, note: 'err', priority: 2 },
  { pattern: /l[oó]s pr[oó]d[uúü]ct[oó]\(s\) q[uúü][eé] t[ií][eé]n[eé]s/i, action: { type: 'END_OK' }, note: 'ok', priority: 2, intents: ['getChemicalProducts', 'getChemicalProductsByClient'] },
  { pattern: /D[ií]str[ií]b[uúü]c[ií]ón d[eé] c[uúü]lt[ií]v[oó]s p[oó]r cl[ií][eé]nt[eé]s/i, action: { type: 'END_OK' }, note: 'ok', priority: 2, intents: ['getCropDistribution'] },
  { pattern: /[eé]nc[oó]ntré l[oó] s[ií]g[uúü][ií][eé]nt[eé]/i, action: { type: 'END_OK' }, note: 'ok', priority: 2, intents: ['getActiveMatterChemicalProducts', 'getChemicalProducts', 'getChemicalProductsByClient', 'getCropDistribution', 'getCrops', 'getFertilizers', 'getLastPrice', 'getLastWork', 'getManufacturerProducts', 'getMinPrice', 'getPendingWorks', 'getPlannedCampaignsHistory', 'getPriceVariation', 'getSeedsNeeded', 'searchProducts', 'searchProductsCrops', 'searchProductsFertilizers'] },
  { pattern: /d[ií]sp[oó]n[eé] d[eé]/i, action: { type: 'END_OK' }, note: 'ok', priority: 2, intents: ['getChemicalProducts', 'getChemicalProductsByClient', 'getFertilizers', 'getManufacturerProducts'] },
  { pattern: /H[eé] r[eé]g[ií]str[aá]d[oó]/i, action: { type: 'END_OK' }, note: 'UI added', priority: 2, intents: ['assignPriceProduct'] },
  { pattern: /N[oó] s[eé] [eé]nc[oó]ntr[aá]r[oó]n tr[aá]b[aá]j[oó]s p[eé]nd[ií][eé]nt[eé]s p[aá]r[aá] h[oó]y [eé]n t[uúü]s c[aá]mp[oó]s/i, action: { type: 'END_OK' }, note: 'UI added', priority: 2, intents: ['getPendingWorks'] },
  { pattern: /Pr[oó]d[uúü]ct[oó]:/i, action: { type: 'END_OK' }, note: 'UI added', priority: 2, intents: ['getChemicalProducts'] },
  { pattern: /H[ií]st[oó]r[ií][aá]l d[eé] c[aá]mp[aá]ñ[aá]s/i, action: { type: 'END_OK' }, note: 'UI added', priority: 2, intents: ['getPlannedCampaignsHistory'] },
  { pattern: /y[aá] t[ií][eé]n[eé] [uúü]n[aá] c[aá]mp[aá]ñ[aá] [aá]ct[ií]v[aá]/i, action: { type: 'END_ERR' }, note: 'UI added', priority: 2, intents: ['createPlannedCampaign'] },
  { pattern: /[eé]st[oó]y [eé]sp[eé]c[ií][aá]l[ií]z[aá]d[oó] ún[ií]c[aá]m[eé]nt[eé] [eé]n t[eé]m[aá]s [aá]gríc[oó]l[aá]s;/i, action: { type: 'END_ERR' }, note: 'UI added', priority: 2 },
  { pattern: /h[aá]s cr[eé][aá]d[oó]/i, action: { type: 'END_OK' }, note: 'UI added', priority: 2, intents: ['filterFertilizers'] },
  { pattern: /F[eé]ch[aá] d[eé]l pr[eé]c[ií][oó]/i, action: { type: 'REPLY', reply: '{price_date}' }, note: 'UI added', priority: 3 },
  { pattern: /v[aá]r[ií][eé]d[aá]d/i, action: { type: 'REPLY', reply: 'premium' }, note: 'premium', priority: 3 },
  { pattern: /Y[aá] [eé]x[ií]st[eé]/i, action: { type: 'END_OK' }, note: 'UI added', priority: 2 },
  { pattern: /[aá]ct[uúü][aá]lm[eé]nt[eé] t[ií][eé]n[eé]s/i, action: { type: 'END_OK' }, note: 'UI added', priority: 2 },
  { pattern: /ddddd/i, action: { type: 'REPLY', reply: 'dddd' }, note: 'UI added', priority: 2 },
  { pattern: /H[eé] c[oó]l[oó]c[aá]d[oó] [eé]l c[uúü]lt[ií]v[oó]/i, action: { type: 'END_OK' }, note: 'UI added', priority: 2, intents: ['createPlannedCampaign'] },
  { pattern: /y[aá] cr[eé][aá]d[oó]/i, action: { type: 'END_OK' }, note: 'UI added', priority: 1 },
  { pattern: /F[eé]ch[aá] d[eé] [ií]n[ií]c[ií][oó]/i, action: { type: 'REPLY', reply: '2020-03-02' }, note: 'UI updated', priority: 2, intents: ['createPlannedCampaign', 'createPlannedWork'] },
];

export type ActionResult = 
  | { type: 'REPLY'; message: string; rawResponse: string; materializedReply: string }
  | { type: 'END_OK'; message: string; rawResponse: string }
  | { type: 'END_ERR'; message: string; rawResponse: string }
  | { type: 'RETRY_EXISTS'; message: string; rawResponse: string }
  | { type: 'UNKNOWN'; message: string; rawResponse: string };

export async function detectAction(messages: string[], currentVars: Record<string, string>): Promise<ActionResult> {
  if (!messages || messages.length === 0) {
    return { type: 'UNKNOWN', message: 'No se recibieron mensajes', rawResponse: '' };
  }

  const fullResponse = messages.join('\n');
  const sorted = [...KEYWORD_RULES].sort((a, b) => (a.priority || 99) - (b.priority || 99));

  for (const rule of sorted) {
    if (rule.pattern.test(fullResponse)) {
      if (rule.action.type === 'REPLY') {
        let replyText = rule.action.reply;
        
        // Si es __EXTRACT_FIRST_OPTION__, extraer el texto de la primera opción
        if (replyText === '__EXTRACT_FIRST_OPTION__') {
          const extracted = extractFirstOption(fullResponse);
          if (extracted) {
            replyText = extracted;
          } else {
            // Fallback: si no se puede extraer, enviar "1"
            replyText = '1';
          }
        }
        
        const materializedReply = materialize(replyText, currentVars);
        return {
          type: 'REPLY',
          message: `Regla: ${rule.note} → responder "${materializedReply}"`,
          rawResponse: fullResponse,
          materializedReply
        };
      } else {
        return { type: rule.action.type, message: rule.note, rawResponse: fullResponse };
      }
    }
  }

  return { type: 'UNKNOWN', message: 'No se encontró regla aplicable', rawResponse: fullResponse };
}

// Funciones auxiliares para flow.ts
export function pickRandomCrop(): typeof CROPS_POOL[number] {
  return randomCrop();
}

const CLIENTS_POOL = ['AgroTalavera', 'Finca Los Olivos', 'Agrícola San José', 'El Cortijo', 'La Dehesa'];

export function pickRandomClient(): string {
  return CLIENTS_POOL[Math.floor(Math.random() * CLIENTS_POOL.length)];
}

export function mutateOneVariableForRetry() {
  // Mutar marca para evitar duplicados "ya existe"
  const currentBrand = VARS.brand || DEFAULT_VARS.brand || 'Brand';
  const suffix = Math.random().toString(36).substring(2, 6);
  setVar('brand', `${currentBrand}_${suffix}`);
}

export function extractFirstOption(text: string): string | null {
  console.log('[extractFirstOption] Texto completo recibido:');
  console.log(text);
  console.log('--- FIN TEXTO ---');
  
  // 1. Buscar patrón "Opciones: opcion1, opcion2, opcion3" (case insensitive)
  const optionsMatch = text.match(/opciones:\s*([^,\n]+)/i);
  if (optionsMatch) {
    let firstOption = optionsMatch[1].trim();
    // Remover cualquier punto final
    firstOption = firstOption.replace(/\.$/, '');
    console.log('[extractFirstOption] ✅ Encontrado en "Opciones:":', firstOption);
    return firstOption;
  }
  
  // 2. Buscar patrones numerados como "1) Opción", "1. Opción", "1: Opción"
  const numberedMatch = text.match(/^\s*1[\)\.:\-]\s*(.+)$/m);
  if (numberedMatch) {
    let firstOption = numberedMatch[1].trim();
    // Remover cualquier punto final o coma
    firstOption = firstOption.replace(/[,\.]$/, '');
    console.log('[extractFirstOption] ✅ Encontrado numerado:', firstOption);
    return firstOption;
  }
  
  // 3. Buscar líneas separadas (caso de lista vertical)
  const lines = text.split('\n').map(line => line.trim()).filter(line => line.length > 0);
  for (const line of lines) {
    // Si encuentra una línea que parece ser una opción válida (no es pregunta ni metadata)
    if (!line.match(/opciones:/i) && 
        !line.match(/nombre\s+del?\s+fabricante/i) && 
        !line.match(/que?\s+deseas/i) &&
        line.length > 2 &&
        !line.includes('?')) {
      let firstOption = line.trim();
      // Remover cualquier punto final o coma
      firstOption = firstOption.replace(/[,\.]$/, '');
      console.log('[extractFirstOption] ✅ Encontrado en línea separada:', firstOption);
      return firstOption;
    }
  }
  
  // 4. Fallback: buscar la primera frase que no sea una pregunta
  const sentences = text.split(/[.!?]/).map(s => s.trim()).filter(s => s.length > 2);
  for (const sentence of sentences) {
    if (!sentence.includes('?') && 
        !sentence.match(/opciones/i) && 
        !sentence.match(/nombre/i) &&
        !sentence.match(/fabricante/i)) {
      console.log('[extractFirstOption] ✅ Encontrado como fallback:', sentence);
      return sentence;
    }
  }
  
  console.log('[extractFirstOption] ❌ No se encontró ningún patrón válido');
  return null;
}
